export {
  computeSelectionTextHash,
  createEditorInputRules,
  createEditorInputRulesPlugin,
  createEmptyDoc,
  createSelectionRef,
  docFromJson,
  editorSchema,
  getInputRules,
  replaceSelectionWithPlainText,
  verifySelectionHash,
  type InputRuleDescriptor,
  type ProseMirrorJson,
  type SelectionRef,
} from "../../../../shared/editor/prosemirror";
